notifications:
  email: false

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=alphacep/kaldi-manylinux:latest

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
  - ls wheelhouse/

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: $FILENAME
  skip_cleanup: true
  on:
    tags: true
